telemetry:
  enabled: true
  interval: 10
  address: localhost:8888

grpc_server:
  listen_address: ${GRPC_SERVER_LISTEN_ADDRESS}

processing:
  processing_servers_list:
    - "localhost:50052"
    - "localhost:50053"
    - "localhost:50054"