telemetry:
  enabled: true
  interval: 10
  address: localhost:8888

grpc_server:
  listen_address: ${GRPC_SERVER_LISTEN_ADDRESS}

processing:
  processing_servers_list:
    - ${GRPC_SERVER_PROCESSING_ADDRESS}

logstash:
  url: ${LOGSTASH_URL}
