prometheus:
  url: ${PROMETHEUS_URL}

grpc_server:
  listen_address: ${GRPC_SERVER_LISTEN_ADDRESS}

processing:
  processing_servers_list:
    - ${GRPC_SERVER_PROCESSING_ADDRESS}

logstash:
  url: ${LOGSTASH_URL}
