version: '3.8'

networks:
  local-net:
    external: true

services:
  zg_router:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: zg_router
    env_file:
      - .env-docker
    networks:
      - local-net  
    volumes:
      - .:/app
    restart: unless-stopped
